classdef nrWavegenSSBurstConfig < comm.internal.ConfigBase
%nrWavegenSSBurstConfig SS Burst configuration for 5G waveform generation
%   CFGSSB = nrWavegenSSBurstConfig creates a synchronization signal (SS)
%   burst configuration object that describes the subcarrier spacing of the
%   SS burst, its placement in time and frequency, as well as its power and
%   payload. Use this object in the SSBurst property of the <a
%   href="matlab:help('nrDLCarrierConfig')">nrDLCarrierConfig</a>
%   object, which configures a 5G downlink waveform generated by 
%   <a href="matlab:help('nrWaveformGenerator')">nrWaveformGenerator</a>.
%
%   By default, the nrWavegenSSBurstConfig object configures the SS burst
%   to carry the master information block (MIB). This SS burst is formed by
%   four active SS blocks and has a periodicity of 20 ms, which is the
%   default value for initial cell selection. The default object represents
%   an SS burst in the center of a carrier with 15 kHz subcarrier spacing
%   (block pattern Case A). To change the frequency location of the SS
%   burst, set NCRBSSB and KSSB to the desired nonempty value.
%
%   CFGSSB = nrWavegenSSBurstConfig(Name,Value) creates an SS Burst
%   configuration object, CFGSSB, with the specified property Name set to
%   the specified Value. You can specify additional name-value pair
%   arguments in any order as (Name1,Value1,...,NameN,ValueN).
%
%   nrWavegenSSBurstConfig properties:
%
%   Enable                  - Flag turning SS burst on or off (true (default), false)
%   Power                   - Power scaling in dB (default 0)
%   BlockPattern            - SS block pattern 
%                             ('Case A' (default), 'Case B', 'Case C', 'Case D', 'Case E', 'Case F', 'Case G')
%   TransmittedBlocks       - Bitmap for block transmission in 5 ms half-frame (default [1 1 1 1])
%   Period                  - Period and offset of SS burst in ms 
%                             (5, 10, 20 (default), 40, 80, 160)
%   NCRBSSB                 - RB offset from Point A (0...2199) (default [])
%   KSSB                    - Subcarrier offset (0...23) (default 0)
%   DataSource              - Source of SS burst payload (default 'MIB')
%   DMRSTypeAPosition       - First DM-RS symbol position for type A PDSCH transmissions (2 (default), 3)
%   CellBarred              - Flag for cell barring (true, false (default))
%   IntraFreqReselection    - Flag for intra-frequency reselection (true, false (default))
%   PDCCHConfigSIB1         - Configuration type of SIB1 PDCCH (0...255) (default 0)
%   SubcarrierSpacingCommon - SIB1 subcarrier spacing in kHz (15 (default), 30, 60, 120)
%
%   Example 1:
%   % Create a default object specifying an SS burst at a 15 kHz SCS
%
%   ssb = nrWavegenSSBurstConfig;
%   cfgDL = nrDLCarrierConfig;
%   cfgDL.SSBurst = ssb;
%
%   Example 2: 
%   % Create an SS burst configuration object at a 120 kHz SCS, with a
%   % custom frequency offset
%
%   ssb = nrWavegenSSBurstConfig;
%   ssb.BlockPattern = 'Case D';
%   ssb.TransmittedBlocks = ones(1, 64);
%
%   cfgDL = nrDLCarrierConfig('FrequencyRange', 'FR2', 'ChannelBandwidth', 100);
%   cfgDL.SCSCarriers{1} = nrSCSCarrierConfig('SubcarrierSpacing', 120);
%   cfgDL.BandwidthParts{1} = nrWavegenBWPConfig('SubcarrierSpacing', 120);
%
%   % Custom frequency offset at a third of the carrier size:
%   ssb.NCRBSSB = round(cfgDL.SCSCarriers{1}.NSizeGrid/3);
%   ssb.KSSB = 2*4;
%
%   cfgDL.SSBurst = ssb;
% 
% See also nrDLCarrierConfig, nrWaveformGenerator

%   Copyright 2020-2024 The MathWorks, Inc.
  
%#codegen

    properties    
    
        %Enable Flag to turn SS burst on or off in waveform generation
        % Specify Enable as a logical scalar. This flag determines the presence
        % of the SS burst in the generated 5G waveform. The default is true.
        Enable (1,1) logical = true;

        %Power Power scaling in dB
        % Specify Power in dB as a real scalar or row vector that expresses the
        % amount by which each SS block is scaled. If Power is a scalar, the
        % same power applies to all SS blocks in the SS burst. If Power is a
        % vector, it must be the same size as TransmittedBlocks and the powers
        % apply to each SS block in the SS burst. The default is 0 dB.
        Power (1,:) {mustBeNonempty, mustBeNumeric, mustBeReal, mustBeFinite} = 0;

        %BlockPattern SS block pattern
        % Specify BlockPattern as one of {'Case A', 'Case B', 'Case C', 'Case
        % D', 'Case E', 'Case F', 'Case G'}, as per TS 38.213 Section 4.1.
        % Cases A, B, and C correspond to Frequency Range 1 (FR1) and to a
        % subcarrier spacing equal to 15 kHz, 30 kHz and 30 kHz respectively.
        % Cases D, E, F and G correspond to Frequency Range 2 (FR2) and to a
        % subcarrier spacing equal to 120 kHz, 240 kHz, 480 kHz and 960 kHz,
        % respectively. The default is 'Case A'.
        BlockPattern = 'Case A';

        %TransmittedBlocks Bitmap indicating block transmission in a 5 ms half-frame burst
        % Specify TransmittedBlocks as a 4- or 8-bit binary vector for
        % Frequency Range 1 (FR1) and as a 64-bit binary vector for Frequency
        % Range 2 (FR2). This binary vector indicates which SS blocks are
        % activated within the SS burst. The default is [1 1 1 1].
        TransmittedBlocks = [1 1 1 1];

        %Period Period and offset of the SS burst
        % Specify the period and offset of the SS burst as [period offset] in
        % milliseconds. The period must be one of {5, 10, 20, 40, 80, 160} and
        % the offset must be a multiple of 5 ms. The default is 20, which
        % indicates a 0 ms offset.
        Period (1,:) = 20;

        %NCRBSSB RB offset from Point A
        % Specify NCRBSSB as a scalar nonnegative integer no greater than 2199
        % or as an empty vector ([]). This property specifies the frequency
        % offset of the SS burst in resource blocks (RB) relative to Point A.
        % For block patterns Case A, B and C, the NCRBSSB units are expressed
        % in terms of 15 kHz subcarrier spacing; for Case D and E, units are
        % expressed in terms of 60 kHz subcarrier spacing. When NCRBSSB is
        % empty ([]), the SS burst is automatically placed in the center of the
        % carrier whose subcarrier spacing is denoted by BlockPattern. The
        % default is [].
        NCRBSSB = [];

        %KSSB Subcarrier offset
        % Specify KSSB as a scalar nonnegative integer. This property further
        % increases the frequency offset of the SS burst from Point A by KSSB
        % subcarriers. For frequency range 1 (corresponding to BlockPattern
        % Case A, B, or C) and when SubcarrierSpacingCommon is 15, the KSSB
        % range is [0 11] and units are expressed in terms of 15 kHz subcarrier
        % spacing. For frequency range 1 and when SubcarrierSpacingCommon is
        % 30, the KSSB range is [0 23] and units are expressed in terms of 15
        % kHz subcarrier spacing. For frequency range 2 (corresponding to
        % BlockPattern Case D, E, F, or G) the KSSB range is [0 11]. For
        % BlockPattern Case D and Case F, the units of of KSSB are given by
        % SubcarrierSpacingCommon. For BlockPattern Case F and Case G, the
        % units of KSSB are given by the subcarrier spacing of the SSB. This
        % property applies when NCRBSSB is not empty ([]), which corresponds
        % to a custom frequency offset. The default is 0.
        KSSB (1,1) {mustBeNumeric, mustBeInteger, mustBeNonnegative, mustBeLessThanOrEqual(KSSB, 23)} = 0;

        %AntennaMapping Antenna mapping vector
        % Specify AntennaMapping with a vector of ordered unique positive
        % integers to map the logical ports to columns in the output
        % waveform. The default is [], indicating that the generated SS
        % blocks are mapped to all output columns.
        AntennaMapping (1,:) = [];

        %SSBlockPrecodingMatrix SS block precoding matrix
        % Specify SSBlockPrecodingMatrix with a complex matrix of size
        % Ncolumns-by-Nblocks, where Ncolumns is the number of columns in
        % the output waveform and Nblocks is the number of blocks as
        % indicated by the length of TransmittedBlocks. When AntennaMapping
        % empty, the generated SS blocks will be mapped as indicated by
        % this property. The default is [], indicating no precoding on SS
        % blocks.
        SSBlockPrecodingMatrix = [];

        %DataSource Source of SS burst payload
        % Specify DataSource as one of {'MIB', 'PN9-ITU', 'PN9', 'PN11',
        % 'PN15', 'PN23'}, as a cell array containing one of the abovementioned
        % options and a numeric scalar that is the random seed (e.g.,
        % {'PN9',7}), or as a 24-bit binary vector. If the seed is not
        % specified, then all shift registers are initialized with an active
        % state. The default is 'MIB'.
        DataSource = 'MIB';

        %DMRSTypeAPosition First DM-RS symbol position for type A PDSCH transmissions
        % Specify the first DM-RS symbol position for type A PDSCH
        % transmissions as 2 or 3. The default is 2. This property applies when
        % DataSource is set to 'MIB'.
        DMRSTypeAPosition (1,1) {mustBeMember(DMRSTypeAPosition, [2 3])} = 2;

        %CellBarred Flag for cell barring
        % Specify CellBarred as a scalar logical. A true value indicates that
        % the cell allows UEs to camp on this cell. The default is false. This
        % property applies when DataSource is set to 'MIB'.
        CellBarred (1,1) logical = false;

        %IntraFreqReselection Flag for intra-frequency reselection
        % Specify IntraFreqReselection as a scalar logical. A true value
        % allows reselection of same-frequency cells. The default is false.
        % This property applies when DataSource is set to 'MIB'.
        IntraFreqReselection (1,1) logical = false;

        %PDCCHConfigSIB1 Configuration of SIB1 PDCCH
        % Specify the configuration type of the System Information Block Type 1
        % (SIB1) as a scalar integer in the range 0...255. The default is 0.
        % This property applies when DataSource is set to 'MIB'.
        PDCCHConfigSIB1 (1,1) {mustBeNumeric, mustBeInteger, mustBeNonnegative, mustBeLessThanOrEqual(PDCCHConfigSIB1, 255)} = 0;

        %SubcarrierSpacingCommon SIB1 subcarrier spacing in kHz
        % Specify the subcarrier spacing of the System Information Block Type 1
        % (SIB1) in kHz as a numeric scalar that is either 15 or 30 for
        % frequency range 1 (FR1) and either 60 or 120 for frequency range 2
        % (FR2). The default is 15. This property applies when DataSource is
        % set to 'MIB' or when BlockPattern is Case D or E (FR2) and NCRBSSB is
        % not empty ([]), which corresponds to a custom frequency offset.
        SubcarrierSpacingCommon (1,1) {mustBeMember(SubcarrierSpacingCommon, [15 30 60 120])} = 15;
    end

    % Constant, hidden properties
    properties (Constant,Hidden)
        BlockPattern_Values = {'Case A', 'Case B', 'Case C', 'Case D', 'Case E', 'Case F', 'Case G'};
        DataSource_Values = {'MIB', 'PN9', 'PN9-ITU', 'PN11', 'PN15', 'PN23'}
        Period_Options = [5, 10, 20, 40, 80, 160];
    end

    properties (Dependent = true, Hidden = true)
        NumColumns
    end

    methods
        function obj = nrWavegenSSBurstConfig(varargin)
            obj@comm.internal.ConfigBase(varargin{:});
        end

        function obj = set.BlockPattern(obj,val)
            prop = 'BlockPattern';
            val = validateEnumProperties(obj, prop, val);

            obj.(prop) = '';
            obj.(prop) = val;
        end

        function obj = set.TransmittedBlocks(obj,val)
            prop = 'TransmittedBlocks';
            temp = val;
            coder.varsize('temp',[1 64],[0 1]);
            validateattributes(temp,{'numeric'},{'binary','row'}, ...
                [class(obj) '.' prop], prop);

            % Lengths other than 4, 8, 64 error at edit time.
            % Invalid lengths for a given FR error at
            % nrDLCarrierConfig.validateConfig.
            coder.internal.errorIf(~any(length(temp)==[4 8 64]), ...
                'nr5g:nrWaveformGenerator:InvalidTxBlocks');

            obj.(prop) = temp;
        end

        function obj = set.Period(obj,val)
            prop = 'Period';
            coder.varsize('temp',[1 2],[0 1]);
            temp = val;

            validateattributes(temp,{'numeric'},{'nonempty','finite','nonnegative'},[class(obj) '.' prop],prop);

            coder.internal.errorIf(~any(temp(1)==obj.Period_Options),'nr5g:nrWaveformGenerator:InvalidSSBPeriod');
            if ~isscalar(temp)
                validateattributes(temp,{'numeric'},{'numel',2},[class(obj) '.' prop],prop);
                coder.internal.errorIf(mod(temp(2),5) || temp(2)>=temp(1),'nr5g:nrWaveformGenerator:InvalidSSBHalfFrameOffset');
            end
            obj.(prop) = temp;
        end

        function obj = set.NCRBSSB(obj,val)
            prop = 'NCRBSSB';
            % To allow codegen for varying length in a single function script
            temp = val;
            coder.varsize('temp',[1 1],[1 1]);
            if ~(isnumeric(temp) && isempty(temp))
                validateattributes(temp,{'numeric'},{'scalar','integer','nonnegative','<=',2199},[class(obj) '.' prop],prop);
            end
            obj.(prop) = temp;
        end

        function obj = set.AntennaMapping(obj,val)
            prop = 'AntennaMapping';
            if ~isempty(val)
                validateattributes(val,{'numeric'}, ...
                    {'integer','positive'}, ...
                    [class(obj) '.' prop],prop);
                coder.internal.errorIf(~isequal(val,unique(val,'stable')), ...
                    'nr5g:nrWaveformGenerator:NonuniqueAntennaMapping');
            end
            obj.(prop) = val;
        end

        function obj = set.SSBlockPrecodingMatrix(obj,val)
            prop = 'SSBlockPrecodingMatrix';
            if ~isempty(val)
                validateattributes(val,{'numeric'}, ...
                    {'2d','nonnan','finite'}, ...
                    [class(obj) '.' prop],prop);
            end
            obj.(prop) = val;
        end

        function obj = set.DataSource(obj,val)
            prop = 'DataSource';
            if iscell(val)
                srcOptions = {'PN9-ITU', 'PN9', 'PN11', 'PN15', 'PN23'};
                validateattributes(val,{'cell'},{'numel', 2},[class(obj) '.' prop],prop);
                temp2 = validatestring(val{1}, srcOptions, [class(obj) '.' prop], prop);
                validateattributes(val{2},{'numeric'},{'scalar', 'integer', 'nonnegative'},[class(obj) '.' prop],prop);
                temp = {temp2 val{2}};
            elseif ischar(val) || isstring(val)
                srcOptions = {'MIB', 'PN9-ITU', 'PN9', 'PN11', 'PN15', 'PN23'};
                temp = validatestring(val, srcOptions, [class(obj) '.' prop], prop);
            else
                temp = val;
                validateattributes(temp,{'numeric'},{'vector', 'integer','binary', 'numel', 24},[class(obj) '.' prop],prop);
            end
            obj.(prop) = temp;
        end

        function validateConfig(obj)
            fr1 = any(strcmp(obj.BlockPattern, {'Case A', 'Case B', 'Case C'}));

            %% BlockPattern & TransmittedBlocks
            coder.internal.errorIf(fr1 && ~any(length(obj.TransmittedBlocks)==[4 8]), ...
                'nr5g:nrWaveformGenerator:InvalidTxBlocks');
            coder.internal.errorIf(~fr1 && length(obj.TransmittedBlocks)~=64, ...
                'nr5g:nrWaveformGenerator:InvalidTxBlocks');

            %% BlockPattern & SubcarrierSpacingCommon
            SCSCommonActive = (~fr1 && ~isempty(obj.NCRBSSB)) || ~isInactiveProperty(obj, 'SubcarrierSpacingCommon');
            coder.internal.errorIf( SCSCommonActive && xor(fr1, obj.SubcarrierSpacingCommon<=30), ...
                'nr5g:nrWaveformGenerator:InvalidSCSSSB', obj.SubcarrierSpacingCommon);

            %% BlockPattern & KSSB
            if ~isInactiveProperty(obj, 'KSSB')
                % KSSB is validated only if it is active
                coder.internal.errorIf(~fr1 && obj.KSSB>11, ...
                    'nr5g:nrWaveformGenerator:InvalidKSSB', obj.KSSB);
                coder.internal.errorIf(SCSCommonActive && obj.SubcarrierSpacingCommon~=30 && obj.KSSB>11, ...
                    'nr5g:nrWaveformGenerator:InvalidKSSBFR1', obj.KSSB);
            end

            %% Power & TransmittedBlocks
            if (length(obj.Power) > 1)
                coder.internal.errorIf(length(obj.Power)~=length(obj.TransmittedBlocks), ...
                    'nr5g:nrWaveformGenerator:InvalidSSBPower',length(obj.Power),length(obj.TransmittedBlocks));
            end

            %% AntennaMapping and SSBlockPrecodingMatrix and TransmittedBlocks
            if ~isempty(obj.SSBlockPrecodingMatrix)
                coder.internal.errorIf(size(obj.SSBlockPrecodingMatrix,2)~=numel(obj.TransmittedBlocks), ...
                    'nr5g:nrWaveformGenerator:InvalidSSBPrecodingMatrixNumCols', ...
                    size(obj.SSBlockPrecodingMatrix,2),numel(obj.TransmittedBlocks));
                if ~isempty(obj.AntennaMapping)
                    coder.internal.errorIf(numel(obj.AntennaMapping)~=size(obj.SSBlockPrecodingMatrix,1), ...
                        'nr5g:nrWaveformGenerator:IncompatibleSSBPrecodingMatrixSize', ...
                        numel(obj.AntennaMapping),size(obj.SSBlockPrecodingMatrix,1));
                end
            end
        end

        function numCols = get.NumColumns(obj)
            if ~isempty(obj.AntennaMapping)
                numCols = max(obj.AntennaMapping,[],'all');
            else
                if isempty(obj.SSBlockPrecodingMatrix)
                    numCols = [];
                else
                    numCols = size(obj.SSBlockPrecodingMatrix,1);
                end
            end
        end

    end

    methods (Hidden = true)

        function P = calculatePrecodeAndMapMatrix(obj,numColumns)

            % Get number of blocks
            numBlocks = numel(obj.TransmittedBlocks);

            if isempty(obj.AntennaMapping) && isempty(obj.SSBlockPrecodingMatrix)

                % Both AntennaMapping and SSBlockPrecodingMatrix are empty
                % - replicate all blocks on all columns
                P = ones(numColumns,numBlocks);
                
            elseif isempty(obj.SSBlockPrecodingMatrix)

                % Only AntennaMapping is non-empty - replicate all blocks 
                % on selected columns
                P = zeros(numColumns,numBlocks);
                for i = 1:numel(obj.AntennaMapping)
                    P(obj.AntennaMapping(i),:) = 1;
                end

            elseif isempty(obj.AntennaMapping)

                % Only SSBlockPrecodingMatrix is non-empty - precode blocks
                % and map to output starting from the first column
                P = [obj.SSBlockPrecodingMatrix; zeros(numColumns-size(obj.SSBlockPrecodingMatrix,1), numBlocks)];

            else

                % Both AntennaMapping and SSBlockPrecodingMatrix are
                % non-empty - precode blocks and map to selected columns
                P1 = obj.SSBlockPrecodingMatrix;
                P2 = zeros(numColumns,size(P1,1));
                antInd = sub2ind(size(P2),(obj.AntennaMapping)',(1:numel(obj.AntennaMapping))');
                P2(antInd) = 1;
                P = P2*P1;
                
            end

        end

    end

    methods (Access = protected)
        function flag = isInactiveProperty(obj, prop)
            % Controls the conditional display of properties

            flag = false;
            if any(strcmp(prop, {'DMRSTypeAPosition'; 'CellBarred'; 'IntraFreqReselection'; ...
                    'PDCCHConfigSIB1'; 'SubcarrierSpacingCommon'}))
                if iscell(obj.DataSource)
                    flag = true;
                else
                    flag = ~strcmpi(obj.DataSource, 'MIB');
                end
            end

            if strcmp(prop, 'KSSB')
                flag = isempty(obj.NCRBSSB);
            end
        end

        function groups = getPropertyGroups(obj)
            mainPropList = {'Enable'; 'Power'; 'BlockPattern'; 'TransmittedBlocks'; 'Period'; 'NCRBSSB'; 'KSSB'; 'AntennaMapping'; 'SSBlockPrecodingMatrix'};
            mainPropVal  = {obj.Enable; obj.Power; obj.BlockPattern; obj.TransmittedBlocks; obj.Period; obj.NCRBSSB; obj.KSSB; obj.AntennaMapping; obj.SSBlockPrecodingMatrix};
            mainPropActive = cellfun(@(x) ~isInactiveProperty(obj, x), mainPropList);
            fr2 = any(strcmpi(obj.BlockPattern, {'Case D', 'Case E', 'Case F', 'Case G'}));
            SCSCommonAtTop = fr2 && ~isempty(obj.NCRBSSB);
            if SCSCommonAtTop
                mainPropList = [mainPropList; 'SubcarrierSpacingCommon'];
                mainPropVal = [mainPropVal; obj.SubcarrierSpacingCommon];
                mainPropActive = [mainPropActive; true];
            end

            mibPropList = {'DataSource'; 'DMRSTypeAPosition'; 'CellBarred'; 'IntraFreqReselection'; ...
                'PDCCHConfigSIB1'};
            mibPropVal  = {obj.DataSource; obj.DMRSTypeAPosition; obj.CellBarred; obj.IntraFreqReselection; ...
                obj.PDCCHConfigSIB1};
            mibPropActive = cellfun(@(x) ~isInactiveProperty(obj, x), mibPropList);

            if ~SCSCommonAtTop
                mibPropList = [mibPropList; 'SubcarrierSpacingCommon'];
                mibPropVal = [mibPropVal; obj.SubcarrierSpacingCommon];
                % SubcarrierSpacingCommon shows up in Payload group only when
                % DataSource = MIB and for FR1
                mibPropActive = [mibPropActive; mibPropActive(end)&&~SCSCommonAtTop];
            end

            groups = [matlab.mixin.util.PropertyGroup(cell2struct(mainPropVal(mainPropActive), mainPropList(mainPropActive))) ...
                matlab.mixin.util.PropertyGroup(cell2struct(mibPropVal(mibPropActive), mibPropList(mibPropActive)), 'Payload:')];
        end
    end
end
