function [kRefTable,dmrsSCPattern,nDMRSSC] = ptrsSubcarrierInfo(dmrsType)
%ptrsSubcarrierInfo Provides the subcarrier related information for PT-RS
%
%   Note: This is an internal undocumented function and its API and/or
%   functionality may change in subsequent releases.
%
%   [KREFTABLE,DMRSSCPATTERN,NDMRSSC] = nr5g.internal.pxsch.ptrsSubcarrierInfo(DMRSTYPE)
%   returns the table of possible resource element offset for PTRS
%   KREFTABLE, the DM-RS subcarrier locations pattern in a resource block
%   DMRSSCPATTERN and the number of DM-RS subcarriers in a resource block,
%   according to the input DM-RS configuration type DMRSTYPE.

%   Copyright 2019-2013 The MathWorks, Inc.

%#codegen

    % Tables 6.4.1.2.2.1-1/7.4.1.2.2-1, TS 38.211
    % Defined relative to the single symbol DM-RS port subsets  
    if dmrsType == 1
        % DM-RS type 1, p = 0...3 ports
        kRefTable = [0 2 6 8;...  
                     2 4 8 10;...
                     1 3 7 9;...
                     3 5 9 11;...
                     % p = 4...7 are not for PT-RS  
                     0 0 0 0;...
                     0 0 0 0;...
                     0 0 0 0;...
                     0 0 0 0;...                         
                     % p = 8...11
                     4 6 10 0;...
                     6 8 0  2;...
                     5 7 11 1;...
                     7 9 1  3];

        % DM-RS subcarrier locations pattern per RB per port
        dmrsSCPattern = [0:2:10; 1:2:11];
        % Number of subcarriers carrying DM-RS symbols per RB per port
        nDMRSSC = 6;
    else
        % DM-RS type 2, p = 0...5 ports
        kRefTable = [0 1 6 7;...
                     1 6 7 0;...
                     2 3 8 9;...
                     3 8 9 2;...
                     4 5 10 11;...
                     5 10 11 4;...
                     % p = 6... 11 are not for PT-RS
                     0 0 0 0;...
                     0 0 0 0;...
                     0 0 0 0;...
                     0 0 0 0;... 
                     0 0 0 0;...
                     0 0 0 0;...
                     % p = 12...17
                     6  7  0 1;...
                     7  0  1 6;...
                     8  9  2 3;...
                     9  2  3 8;...
                     10 11 4 5;...
                     11 4  5 10];

        % DM-RS subcarrier locations pattern per RB per port
        dmrsSCPattern = [0 1 6 7; 2 3 8 9; 4 5 10 11];
        % Number of subcarriers carrying DM-RS symbols per RB per port
        nDMRSSC = 4;
    end

end
